### PR TITLE
Test port from c

### PR DESCRIPTION
**Pull request by nsg**
This is a quick and dirty port/copy paste from the c client.

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson okay, this builds nice for me and opens a empty window (no logic to catch the close events so you need to ^C it.

`cmake .`, `make` and finaly `./klient`.

It was 5-6 years since I touched c++ so I'm a little uncertain what best practices there are, I made a quick class inside a namespace. A constructor and one destructor. Everything called from main().

Crazy-code?

**Comment by nsg** [comment]
Okay, this works. We now loads the old code base imported from [client](https://github.com/konstructs/client). This is a hack :)

There is still a segfault in there that needs to be tracked down.

**Comment by petterarvidsson** [comment]
@nsg It works, so I would say it's a good starting point.

**Comment by petterarvidsson** [comment]
:+1:

**Pull request merged**
